service: cloudwatch-slack-alert
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 30
  environment:
    SLACK_WEBHOOK_URL: ${env:SLACK_WEBHOOK_URL}
    SLACK_CHANNEL: ${env:SLACK_CHANNEL}
    SLACK_USER: ${env:SLACK_USER}
    LOG_GROUPS: ${env:LOG_GROUPS}
    POLL_PERIOD_MS: ${env:POLL_PERIOD_MS}
    FILTER_PATTERN: ${env:FILTER_PATTERN}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:FilterLogEvents"
      Resource: "arn:aws:logs:us-east-1:*:log-group:/aws/lambda/*"

plugins:
  - serverless-offline
  - serverless-offline-scheduler

functions:
  send-error-message:
    handler: src/functions/cron/send-error-message.handler
    timeout: 15
    events:
      - schedule: rate(5 minutes)